# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeSpeak' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeSpeak
#  pod 'OpenTok', '~> 2.9'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'RealmSwift'
  pod 'AFNetworking', '~> 3.1'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'Cosmos', '~> 7.0'
end
